Lab4RolandShum: CS170::ListLab Namespace Reference
CS170::ListLab Namespace Reference
namespace Warboats
Functions
void PrintList (struct Node *list)
Given the head of a linked list, prints the entire linked list out.
int Count (struct Node *list)
Given the head of a linked list, counts the number of nodes in said list.
void AddToEnd (Node **pList, int value)
Given a linked list, adds a new node to the end of it. Will create a new node if passed in NULL.
void AddToFront (Node **pList, int value)
Given a linked list, adds a new node to front of it and sets the head to that new node.
Node * FindItem (Node *list, int value)
Given a linked list, searches through the linked list for the given value and returns the first node found with that value. If no nodes are found with that value, returns NULL.
void FreeList (Node *pList)
Given the head of the linked list, frees all the nodes in the linked list.
void Insert (Node **pList, int value, int position)
Given a linked list, adds a new node with the given value in the position specified. Valid placements range from 0 to the size of the linked list. If the position given is invalid, the function will not add a new node.
Detailed Description
namespace Warboats
Function Documentation
void CS170::ListLab::AddToEnd (Node ** pList, int value)
Given a linked list, adds a new node to the end of it. Will create a new node if passed in NULL.
Parameters
pList Pointer to the head of the linked list.
value The value the new node will hold.
Definition at line 137 of file List.cpp.
Referenced by Insert().
     {
       // If the list is NULL, create a node there.
       if (*pList == NULL)
       {
         *pList = MakeNode(value);
         return;
       }
       // Traverse to end of list.
       while((*pList)->next != NULL)
       {
         pList = &((*pList)->next);
       }
       // Now we create a node and add it to the end.
       (*pList)->next = MakeNode(value);
     }
void CS170::ListLab::AddToFront (Node ** pList, int value)
Given a linked list, adds a new node to front of it and sets the head to that new node.
Parameters
pList Pointer to the head of the linked list.
value The value the new node will hold.
Definition at line 168 of file List.cpp.
Referenced by Insert().
     {
       // Make a new node.
       Node *newNode = MakeNode(value);
       // Set this new node to the head of the linked list..
       newNode->next = *pList;
       *pList = newNode;
     }
int CS170::ListLab::Count (struct Node * list)
Given the head of a linked list, counts the number of nodes in said list.
Parameters
list Pointer to the head of the linked list.
Returns
The number of nodes in the given linked list.
Definition at line 112 of file List.cpp.
Referenced by Insert().
     {
       int count = 0; // Number of nodes in the list
       while (list)
       {
         count++;
         list = list->next;
       }
       return count;
     }
Node* CS170::ListLab::FindItem (Node * list, int value)
Given a linked list, searches through the linked list for the given value and returns the first node found with that value. If no nodes are found with that value, returns NULL.
Parameters
list Pointer to a node that is the head of the linked list.
value The value of the node to find.
Returns
A pointer to the node containing the given value. Returns NULL if none are found.
Definition at line 196 of file List.cpp.
     {
       // Traverse to the end of list.
       while(list != NULL)
       {
         // If the currunt node is the value.
         if(value == list->number)
         {
           // Return the node.
           return list;
         }
         // Else continue looking through the list.
         list = list->next;
       }
       // We have not found it. Return NULL.
       return NULL;
     }
void CS170::ListLab::FreeList (Node * pList)
Given the head of the linked list, frees all the nodes in the linked list.
Parameters
pList Pointer to the head of the linked list.
Definition at line 223 of file List.cpp.
     {
       // Keep a pointer to the next node.
       Node *nextNode = pList->next;
       // Keep a pointer to the next node, free the current one.
       while(pList != NULL)
       {
         // Set the new pointer.
         nextNode = pList->next;
         // free the current one.
         delete pList;
         // Point to next in list.
         pList = nextNode;
       }
     }
void CS170::ListLab::Insert (Node ** pList, int value, int position)
Given a linked list, adds a new node with the given value in the position specified. Valid placements range from 0 to the size of the linked list. If the position given is invalid, the function will not add a new node.
Ie. In the list of [2, 3, 5], 5 will have position 2. Adding a node at position 2 with value of 10 will make [2, 3, 10, 5].
Parameters
pList Pointer to the head of the linked list.
value The value the new node will hold.
position The index position the new node will have.
Definition at line 262 of file List.cpp.
References AddToEnd(), AddToFront(), and Count().
     {
       // Check if position is a valid value in the linked list.
       if(position > Count(*pList) || position < 0)
       {
         // There is none of that position around here.
         return;
       }
       // If we are just placing at position 0, which is head, we add to front.
       if(position == 0)
       {
         AddToFront(pList, value);
         // End function
         return;
       }
       else if(position == Count(*pList)) // Adding to back of array?
       {
         AddToEnd(pList, value);
         // End functions.
         return;
       }
       // Else we add in the middle of list.
       int traverse_count = 0 ;     // How many times do we really need to move?
       Node *curr_node = *pList;
       // Traverse the list until we the next one is where we need to insert.
       while(++traverse_count < position)
       {
         curr_node = curr_node->next;
       }
       // Now we insert between the current node and its next node.
       Insert_Between(MakeNode(value), curr_node, curr_node->next);
     }
void CS170::ListLab::PrintList (struct Node * list)
Given the head of a linked list, prints the entire linked list out.
Parameters
list Pointer to the head of the linked list.
Definition at line 90 of file List.cpp.
     {
       while (list)
       {
         std::cout << list->number << "   ";
         list = list->next;
       }
       std::cout << std::endl;
     }